apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-web-app
  template:
    metadata:
      labels:
        app: mock-web-app
    spec:
      containers:
      - name: app
        image: mock-web-app:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: endpoint
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          value: postgres
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mock-web-app
# spec:
#   type: NodePort
#   selector:
#     app: mock-web-app
#   ports:
#     - protocol: TCP
#       port: 8080
