name: CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Build web-app image
      run: minikube image build -t mock-web-app:latest web-app

    - name: Deploy web-app to minikube
      run: kubectl apply -f k8s/deployment.yaml

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve

    - name: Check web-app
      run: kubectl wait --for=condition=ready pod -l app=mock-web-app

    - name: Check pods
      run: kubectl get pods
